POST http://localhost:5117/breakfasts
Content-Type: application/json

{
    "name": "Vegan Sunshine",
    "description": "Vegan everything! Join us for a healthy breakfast..",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}

###
GET https://localhost:7201/Breakfasts/10408a17-8219-46d4-b5e8-e20135e6ecdf